name: test and scan

on: [push]

jobs:
  go-test:
    uses: jreisinger/github-actions/.github/workflows/go-test.yml@v1.0.1
  trivy-scan:
    uses: jreisinger/github-actions/.github/workflows/trivy-scan.yml@v1.0.1